project_name: server
before:
  hooks:
    - go mod download
builds:
- binary: 9pd
  dir: ./cmd/9pd
  goos:
  - linux
  - windows
  - darwin
  - freebsd
  goarch: 
  - amd64
- binary: sshd
  dir: ./cmd/sshd
  goos:
  - linux
  - windows
  - darwin
  - freebsd
  goarch:
  - amd64
signs:
  - artifacts: all
archives:
- replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    freebsd: FreeBSD
    amd64: x86_64
  format_overrides:
    - goos: windows
      format: zip
checksum:
  name_template: 'checksums'
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
