name: flutter
on:
  push:
    paths:
      - 'flutter/altid_lib/**'
jobs:
  
  build:
    name: Flutter Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - uses: subosito/flutter-action@v1
        with:
          channel: 'stable'
      - name: Get dependencies
        run: flutter pub get
        working-directory: flutter/altid_lib
        
      - name: Tests
        run: flutter test
        working-directory: flutter/altid_lib
