# .github/workflows/release.yaml

on: release
name: release
jobs:
  linux-386:
    name: 9pd linux/386
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: set up go
      uses: actions/setup-go@v1
      with:
        go-version: 1.14
    - name: compile and release
      uses: goreleaser/go-release.action@v1
      with:
        args: release --rm-dist
        workdir:  cmds/9pd
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GOARCH: "386"
        GOOS: linux
  linux-amd64:
    name: 9pd linux/amd64
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: set up go
      uses: actions/setup-go@v1
      with:
        go-version: 1.14
    - name: compile and release
      uses: goreleaser/go-release.action@v1
      with:
        args: release --rm-dist
        workdir:  cmds/9pd
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GOARCH: amd64
        GOOS: linux
  darwin-386:
    name: 9pd darwin/386
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: set up go
      uses: actions/setup-go@v1
      with:
        go-version: 1.14
    - name: compile and release
      uses: goreleaser/go-release.action@v1
      with:
        args: release --rm-dist
        workdir:  cmds/9pd
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GOARCH: "386"
        GOOS: darwin
  darwin-amd64:
    name: 9pd darwin/amd64
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: set up go
      uses: actions/setup-go@v1
      with:
        go-version: 1.14
    - name: compile and release
      uses: goreleaser/go-release.action@v1
      with:
        args: release --rm-dist
        workdir:  cmds/9pd
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GOARCH: amd64
        GOOS: darwin
  windows-amd64:
    name: 9pd windows/amd64
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: set up go
      uses: actions/setup-go@v1
      with:
        go-version: 1.14
    - name: compile and release
      uses: goreleaser/go-release.action@v1
      with:
        args: release --rm-dist
        workdir:  cmds/9pd
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GOARCH: amd64
        GOOS: windows
