# .github/workflows/release.yaml
name: publish releases
on:
  push:
    tags:
      - '*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:

    - name: set up go
      uses: actions/setup-go@v1
      with:
        go-version: 1.14
      id: go
      
    - name: checkout
      uses: actions/checkout@v2
      
    - name: unshallow
      run: git fetch --prune --unshallow
      
    - name: Get Dependencies
      run: |
        go get -v -t -d ./...
        if [ -f Gopkg.toml ]; then
            curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
            dep ensure
        fi
        
    - name: release linux/386
      uses: goreleaser/go-release.action@v1
      with:
        args: release --rm-dist
        workdir:  cmds/9pd
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GOARCH: "386"
        GOOS: linux
  
    - name: release linux/amd64
      uses: goreleaser/go-release.action@v1
      with:
        args: release --rm-dist
        workdir:  cmds/9pd
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GOARCH: amd64
        GOOS: linux

    - name: release darwin/amd64
      uses: goreleaser/go-release.action@v1
      with:
        args: release --rm-dist
        workdir:  cmds/9pd
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GOARCH: amd64
        GOOS: darwin

    - name: release windows/amd64
      uses: goreleaser/go-release.action@v1
      with:
        args: release --rm-dist
        workdir:  cmds/9pd
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GOARCH: amd64
        GOOS: windows
